# Generated by Django 6.0.3 on 2026-03-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translator', '0005_delete_evaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('personality_traits', models.TextField(blank=True, default='')),
                ('current_location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('sleeping', 'Sleeping')], db_index=True, default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('event', 'Event'), ('thought', 'Thought'), ('chat', 'Chat')], db_index=True, default='event', max_length=20)),
                ('content', models.TextField()),
                ('importance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='translator.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('transcript', models.JSONField(default=list)),
                ('participants', models.ManyToManyField(blank=True, related_name='conversations', to='translator.agent')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='translator.simulation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='translator.simulation'),
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('simulation', 'name')},
        ),
        migrations.CreateModel(
            name='SimulationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('world_state', models.JSONField(default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='translator.simulation')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('simulation', 'step_number')},
            },
        ),
    ]
