# Generated by Django 4.2.29 on 2026-03-11 07:46
# Updated: removed AlterField calls for models not yet created (conceptnode, demo,
# demomovement, keywordstrength, runtimestate, spatialmemory) — these will be
# handled in future migrations when those models are added.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0009_demo_conversation_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentstate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="movementrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="personascratch",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
