# Generated by Django 6.0.3 on 2026-03-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0013_rename_conceptnode_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preview_image_url', models.CharField(blank=True, max_length=500)),
                ('maze_name', models.CharField(max_length=255)),
                ('max_agents', models.IntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='environmentstate',
            name='unique_environmentstate_simulation_step',
        ),
        migrations.RemoveConstraint(
            model_name='movementrecord',
            name='unique_movementrecord_simulation_step',
        ),
        migrations.RenameIndex(
            model_name='environmentstate',
            new_name='translator__simulat_64cc1d_idx',
            old_name='translator_environmentstate_sim_step_idx',
        ),
        migrations.RenameIndex(
            model_name='movementrecord',
            new_name='translator__simulat_64e289_idx',
            old_name='translator_movementrecord_sim_step_idx',
        ),
        migrations.AlterUniqueTogether(
            name='environmentstate',
            unique_together={('simulation', 'step')},
        ),
        migrations.AlterUniqueTogether(
            name='movementrecord',
            unique_together={('simulation', 'step')},
        ),
    ]
