# Generated by Django 6.0.3 on 2026-03-17 08:57

from django.db import migrations


def seed_the_ville(apps: object, schema_editor: object) -> None:
    Map = apps.get_model("translator", "Map")  # type: ignore[attr-defined]
    Map.objects.get_or_create(
        id="the_ville",
        defaults={
            "name": "The Ville",
            "description": "A small town simulation world where agents live, work, and interact.",
            "preview_image_url": "",
            "maze_name": "the_ville",
            "max_agents": 25,
            "is_active": True,
        },
    )


def reverse_seed(apps: object, schema_editor: object) -> None:
    Map = apps.get_model("translator", "Map")  # type: ignore[attr-defined]
    Map.objects.filter(id="the_ville").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0014_add_map_model"),
    ]

    operations = [
        migrations.RunPython(seed_the_ville, reverse_seed),
    ]
