# Generated by Django 6.0.3 on 2026-03-17 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0016_add_simulation_owner_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('traits', models.TextField(blank=True, default='')),
                ('backstory', models.TextField(blank=True, default='')),
                ('currently', models.TextField(blank=True, default='')),
                ('lifestyle', models.TextField(blank=True, default='')),
                ('daily_plan', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_simulation', 'In Simulation')], default='available', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='translator.simulation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_character_name')],
            },
        ),
    ]
