version: '3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db/app_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000/api
    depends_on:
      - backend

  ollama:
    extends:
      file: Chatbot/docker-compose.yml
      service: ollama
    networks:
    - home-network
    ports:
      - 11434:11434

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: